# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: .
# Target is a subdirs project 

TEMPLATE = subdirs
CONFIG += debug \
warn_on \
qt
QMAKE_CXXFLAGS_DEBUG = -Werror \
-ansi \
-pedantic
QMAKE_CXXFLAGS_RELEASE = -Werror \
-ansi \
-pedantic
SUBDIRS += src \
           plugins \
           interfaces 
