# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./plugins/affect
# Target is a library:  ../../interfaces/libinterfaces.a

SOURCES += affect.cpp 
HEADERS += affect.h 
TEMPLATE = lib 
CONFIG += release \
          warn_on \
          qt \
          thread \
          plugin 
TARGET = ../../interfaces/libinterfaces.a 
INCLUDEPATH = ../../interfaces 
LIBS += ../../interfaces/libinterfaces.a 
TARGETDEPS += ../../interfaces/libinterfaces.a 
