# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./plugins/id
# Target is a library:  

SOURCES += idpage.cpp 
HEADERS += ../../interfaces/page.h \
           ../../interfaces/master.h \
           ../../interfaces/mtpbrowser.h \
           idform.ui.h \
           idpage.h 
FORMS += idform.ui 
TEMPLATE = lib 
CONFIG += release \
          warn_on \
          qt \
          thread 
INCLUDEPATH = ../../interfaces 
