# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./plugins
# Target is a subdirs project 

TEMPLATE = subdirs
CONFIG += release \
warn_on
SUBDIRS += tell \
           browser \
           drawing \
           splash \
           id \
           affect \
           emit
