# File generated by kdevelop's qmake manager.
# -------------------------------------------
# Subdir relative project main directory: ./plugins
# Target is a subdirs project

TEMPLATE = subdirs
CONFIG += release \
warn_on
SUBDIRS += tell \
           browser \
           drawing \
           splash \
           id \
           cron \
           osdsplash \
           intern
QMAKE_CXXFLAGS_DEBUG += -Werror \
                        -Wall \
                        -ansi \
                        -pedantic \
                        -g3
QMAKE_CXXFLAGS_RELEASE += -Wall \
                          -ansi \
                          -pedantic
