# File generated by kdevelop's qmake manager.
# -------------------------------------------
# Subdir relative project main directory: ./plugins/drawing
# Target is a library:

SOURCES += canvas.cpp \
           painter.cpp
HEADERS += canvas.h \
           painter.h
TEMPLATE = lib
CONFIG += release \
          warn_on \
          qt \
          thread \
          plugin
OBJECTS_DIR = .obj
MOC_DIR = .moc
INCLUDEPATH = ../../interfaces \
../../utils
LIBS += ../../interfaces/libinterfaces.a \
../../utils/libutils.a
TARGETDEPS += ../../interfaces/libinterfaces.a
TARGET = ../../lib/drawing
QMAKE_CXXFLAGS_DEBUG += -Werror \
                        -Wall \
                        -ansi \
                        -pedantic \
                        -Wno-long-long \
                        -g3
QMAKE_CXXFLAGS_RELEASE += -Wall \
                          -ansi \
                          -pedantic \
                          -Wno-long-long
