# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./plugins/drawing
# Target is a library:  ../../interfaces/libinterfaces.a

SOURCES += canvas.cpp \
           painter.cpp 
HEADERS += canvas.h \
           painter.h 
TEMPLATE = lib 
CONFIG += release \
          warn_on \
          qt \
          thread \
          plugin 
TARGET = ../../interfaces/libinterfaces.a 
OBJECTS_DIR = .obj 
MOC_DIR = .moc 
INCLUDEPATH = ../../interfaces 
LIBS += ../../interfaces/libinterfaces.a 
TARGETDEPS += ../../interfaces/libinterfaces.a 
