# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./plugins/tell
# Target is a library:  

SOURCES += tellpage.cpp
HEADERS += tellpage.h \
../../interfaces/master.h \
../../interfaces/mtpbrowser.h \
../../interfaces/page.h
TEMPLATE = lib 
CONFIG += release \
          warn_on \
          qt \
          thread 
INCLUDEPATH = ../../interfaces 
