# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./utils
# Target is a library:  

SOURCES += domutil.cpp 
HEADERS += domutil.h 
TEMPLATE = lib 
CONFIG += release \
          warn_on \
          qt \
          thread \
          staticlib 
OBJECTS_DIR = .obj 
MOC_DIR = .moc 
