# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./utils
# Target is a library:  

TEMPLATE = lib
CONFIG += release \
warn_on \
qt \
thread \
staticlib
SOURCES += domutil.cpp 
HEADERS += domutil.h 
