# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./plugins/splash
# Target is a library:  

TEMPLATE = lib 
CONFIG += release \
          warn_on \
          qt \
          thread 
INCLUDEPATH = ../../interfaces 
SOURCES += splash.cpp 
HEADERS += splash.h \
../../interfaces/master.h \
../../interfaces/page.h
