# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./interfaces
# Target is a library:  

SOURCES += MtpContext.cpp \
           mtpbrowser.cpp
HEADERS += master.h \
           mtpbrowser.h \
           page.h \
           MtpContext.h 
TEMPLATE = lib 
CONFIG += release \
          warn_on \
          qt \
          thread \
          staticlib 
OBJECTS_DIR = .obj 
MOC_DIR = .moc 
