# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./interfaces
# Target is a subdirs project 

TEMPLATE = subdirs 
CONFIG += release \
          warn_on 
