# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./plugins/browser
# Target is a library:  

TEMPLATE = lib 
CONFIG += release \
          warn_on \
          qt \
          thread 
INCLUDEPATH = ../../interfaces 
SOURCES += browserpage.cpp 
HEADERS += browserpage.h \
../../interfaces/master.h \
../../interfaces/mtpbrowser.h \
../../interfaces/page.h
