# File generated by kdevelop's qmake manager.
# -------------------------------------------
# Subdir relative project main directory: ./src
# Target is an application:  ../bin/qnet

DBFILE = qnet.db
LANGUAGE = C++
TEMPLATE = app
CONFIG += debug \
warn_on \
qt \
thread
TARGET = ../bin/qnet
OBJECTS_DIR = .obj
MOC_DIR = .moc
INCLUDEPATH = ../filters \
../utils \
../interfaces
LIBS += ../interfaces/libinterfaces.a \
../filters/libfilters.a \
../utils/libutils.a
TARGETDEPS += ../interfaces/libinterfaces.a \
../filters/libfilters.a \
../utils/libutils.a
SOURCES += main.cpp \
           qnet.cpp \
           telnetmanager.cpp \
           ChatSession.cpp \
           MainChatPage.cpp \
           SessionsSettings.cpp \
           UrlSettings.cpp \
           PrefixSettings.cpp \
           remotecontrol.cpp \
           trayicon.cpp \
           trayicon_x11.cpp \
           mainwin.cpp
HEADERS += qnet.h \
           telnetmanager.h \
           ChatSession.h \
           MainChatPage.h \
           version.h \
           SessionsSettings.h \
           UrlSettings.h \
           PrefixSettings.h \
           remotecontrol.h \
           appearancesettings.ui.h \
           mtpfilterssettings.ui.h \
           trayicon.h \
           mainwin.h \
           guile_global.h
IMAGES += images/filenew \
          images/fileopen \
          images/filesave \
          images/print \
          images/undo \
          images/redo \
          images/editcut \
          images/editcopy \
          images/editpaste \
          images/searchfind
FORMS += qnet_base.ui \
         connectionbox.ui \
         mtpsettings.ui \
         urlsettingsbase.ui \
         prefixsettingsbase.ui \
         fortunesettings.ui \
         appearancesettings.ui \
         mtpfilterssettings.ui \
         sessionssettingsbase.ui \
         tagssettings.ui \
         pluginssettings.ui
QMAKE_CXXFLAGS_DEBUG += -Wall \
                        -ansi \
                        -pedantic \
                        -Wno-long-long \
                        -g3
QMAKE_CXXFLAGS_RELEASE += -Wall \
                          -ansi \
                          -pedantic \
                          -Wno-long-long
QMAKE_LFLAGS_DEBUG = -lguile
QMAKE_LFLAGS_RELEASE = -lguile
