# File generated by kdevelop's qmake manager.
# -------------------------------------------
# Subdir relative project main directory: ./filters
# Target is a library:

SOURCES += BlockFilter.cpp \
           Filter.cpp \
           GlobalFilter.cpp \
           InputFilter.cpp \
           ItemFilter.cpp \
           LineFilter.cpp \
           MtpFilter.cpp \
           MtpRegExp.cpp
HEADERS += BlockFilter.h \
           Filter.h \
           GlobalFilter.h \
           InputFilter.h \
           ItemFilter.h \
           LineFilter.h \
           MtpFilter.h \
           MtpRegExp.h
TEMPLATE = lib
CONFIG += release \
          warn_on \
          qt \
          thread \
          staticlib
QMAKE_CXXFLAGS_DEBUG += -g3
OBJECTS_DIR = .obj
MOC_DIR = .moc
INCLUDEPATH = ../utils \
              ../interfaces
